export default {
  headers: [
    {
      Header: "Customer Name",
      accessor: "customername",
    },
    {
      Header: "Category",
      accessor: "category",
    },
    {
      Header: "Price",
      accessor: "price",
    },
    {
      Header: "Description",
      accessor: "description",
    },
    {
      Header: "Date Posted",
      accessor: "date",
    },
    {
      Header: "Status",
      accessor: "status",
    },
  ],
  tasks: [
    {
      key: 0,
      customername: "Danny Lee",
      category: "Food",
      price: "$1",
      description: "먹다남은 신라면 팝니다.",
      date: "11/22/2022",
      status: "Sold",
      itemId: "itemId1",
    },
    {
      key: 1,
      customername: "Hannah",
      category: "Electronics",
      price: "$100",
      description: "에어팟프로 미개봉 팝니다",
      date: "11/21/2022",
      status: "Selling",
      itemId: "itemId2",
    },
    {
      key: 2,
      customername: "준성",
      category: "Food",
      price: "$11",
      description: "먹다남은 프로틴 팔아요.",
      date: "11/12/2022",
      status: "Sold",
      itemId: "itemId3",
    },
    {
      key: 3,
      customername: "쩡우박",
      category: "Clothes",
      price: "$11",
      description: "비니 팝니다",
      date: "11/01/2022",
      status: "Sold",
      itemId: "itemId4",
    },
    {
      key: 4,
      customername: "sunmoonKim",
      category: "Electronics",
      price: "$111",
      description: "모니터 팝니다",
      date: "10/11/2022",
      status: "Selling",
      itemId: "itemId5",
    },
    {
      key: 5,
      customername: "yangachi",
      category: "Others",
      price: "$100",
      description: "UCLA vs USC 풋볼 티켓 팝니다",
      date: "10/-1/2022",
      status: "Selling",
      itemId: "itemId5",
    },
  ],
};
